### ISSUE TITLE
Error when installing via bower

### ISSUE THREAD

**Issue by badfeather** [briancherne/jquery-hoverIntent#41]
I'm getting the following error when I try to install the plugin via bower:

`ENOTFOUND Package jquery-hoverintent not found`

Any ideas?

**Comment by usmonster** [comment]
@badfeather Is this still an issue? It seems like it could be a caching issue related to the recent GitHub DDoS, according to some similar issues I've seen reported to bower and bower-search.

Also, are you behind a proxy by any chance?

**Comment by badfeather** [comment]
@usmonster Yes, still having the issue. Not on a proxy. An odd one!

**Comment by usmonster** [comment]
Just got a chance to look back at this--turns out you're having trouble because the package is actually in the bower registry as `jquery-hoverIntent` (capital `I`), even though the name in the bower.json file is all lowercase (as per the spec).

Just now realizing that this inconsistency is what issues such as #30 have been trying to communicate, and that it's turning out to be a real problem for some. I guess I can just register an alias for the all-lowercase name...

...Done. Can you please try again with the all-lowercase name and then close the issue if it works for you? (You might need to do a `bower cache clean`.)

**Comment by badfeather** [comment]
Worked! Thanks.

**Comment by badfeather** [comment]
One more note about this. The javascript file still has the capital I in
the filename. Not sure if this is important or not, but I thought I'd point
it out.

On Thu, May 14, 2015 at 8:35 AM, Usman <notifications@github.com> wrote:

> Just got a chance to look back at this--turns out you're having trouble
> because the package is actually in the bower registry as
> jquery-hoverIntent (capital I), even though the name in the bower.json
> file is all lowercase (as per the spec).
>
> Just now realizing that this inconsistency is what issues such as #30
> <https://github.com/briancherne/jquery-hoverIntent/pull/30> have been
> trying to communicate, and that it's turning out to be a real problem for
> some. I guess I can just register an alias for the all-lowercase name...
>
> ...Done. Can you please try again with the all-lowercase name and then
> close the issue if it works for you? (You might need to do a bower cache
> clean.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/briancherne/jquery-hoverIntent/issues/41#issuecomment-102023629>
> .
>



-- 
badfeather.com

**Comment by usmonster** [comment]
Thanks for verifying it's OK for you! And the filename is fine, it's just the `"name"` inside the bower.json must be all-lowercase.
