### ISSUE TITLE
Submit to jsdelivr

### ISSUE THREAD

**Issue by bradvogel** [briancherne/jquery-hoverIntent#44]
http://www.jsdelivr.com/#!jquery.hoverintent looks really outdated

**Comment by usmonster** [comment]
Sure, why not? :)

Added to the v1.9.0 milestone.

(Prerequisite: #32.)

**Comment by minorgod** [comment]
+1

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

**Comment by usmonster** [comment]
If I understand correctly, according to the link in the last comment this issue can be closed, since it would be covered by #48? Though it still looks like there's the same old listing for [`jQuery.hoverIntent`](http://www.jsdelivr.com/projects/jquery.hoverintent), which should be removed altogether in favor of `jquery-hoverintent`... I'm on it in jsdelivr#18007.

In the meantime, I'm closing this one.
