### ISSUE TITLE
1.8.1 on NPM is a mismatch?

### ISSUE THREAD

**Issue by jaswrks** [briancherne/jquery-hoverIntent#67]
Running `npm install jquery-hoverintent@1.8.1` installs a slightly different variation from what I'm seeing in this repo. Compare [this file](https://github.com/briancherne/jquery-hoverIntent/blob/v1.8.1/jquery.hoverIntent.js) to what is installed by NPM. They are both the same version in the docBlock header, but they each have different file contents.

**Comment by usmonster** [comment]
Hey, thanks for spotting this. Yes, this file is in fact very different, because it was published when an unofficial entity (@tacitknowledge) had registered the plugin on NPM and pointed it to their own version.

The official versions on NPM start at 1.9.0, as that's the version when package.json was added. There's no way for me to overwrite/update or even unpublish the older (unofficial) ones in the registry, unfortunately. (I should be able to deprecate them, if you prefer?)

As a workaround, if you really want to install the official 1.8.1, you can take a look at @shama/napa, which should be able to help. But, out of curiosity, is there a specific reason you can't/don't want to install v1.9.0?

Hope this helps!

(I'll close this issue now, but please still respond, if you wish.)

**Comment by jaswrks** [comment]
@usmonster Thanks. There is some work being done on WordPress core to reorganize JS dependencies and to take advantage of NPM as a part of the build process. I ran into this in a review of that work. See: https://core.trac.wordpress.org/ticket/43055#comment:17

Would it be possible to publish a tagged NPM package?
https://docs.npmjs.com/cli/dist-tag

e.g., `npm publish --tag=real-1.8.1`

**Comment by jaswrks** [comment]
> As a workaround, if you really want to install the official 1.8.1, you can take a look at , which should be able to help. But, out of curiosity, is there a specific reason you can't/don't want to install v1.9.0?

There are often far-reaching implications whenever a library is updated in a project as popular as WordPress core. I have every confidence that WordPress will one day move to 1.9.x, but it will likely come after a somewhat lengthy review process, and in a separate issue. At the moment, organizing the build process and being able to collect a proper 1.8.1 distro via NPM is at the forefront.

**Comment by usmonster** [comment]
@jaswrks Thanks, I completely understand not being able to upgrade yet.

To address the issue at hand, would it be acceptable if I simply published a new patch version (`v.1.8.2`) that's exactly the same JS as `v1.8.1`, but which includes a package.json file? I'd just need to create a new branch with a modified history. Then you could update your dependency without having to launch a review process.

Please let me know what you think, and I'll try to do it this weekend. (I might do it anyway, but please let me know if it would serve your use case.)

**Comment by jaswrks** [comment]
Awesome. Sounds like a plan to me.

**Comment by usmonster** [comment]
Update: There's actually already a `v1.8.2` version published to npm (also unauthorized), so I've published `v1.8.3` to supersede prior 1.8.x versions. Please let me know if it's OK for you!

**Comment by jaswrks** [comment]
@usmonster Thank you! I noted your update in this ticket.
https://core.trac.wordpress.org/ticket/43055#comment:22
